spring.datasource.url=jdbc:postgresql://localhost:5432/innovify_db
spring.datasource.username=postgres
spring.datasource.password=postgre
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

server.port=8081

springdoc.swagger-ui.path=/swagger-ui.html
springdoc.api-docs.path=/api-docs

ip.frontend=http://3.21.40.9:4200
jwt.secret=aW5ub3ZpZnktc2tpbGxzd2FwLWp3dC1hdXRoLXNlY3JldC1rZXktMjAyNC1zYWZl
jwt.expiration=18000000
firebase.credentials.path=classpath:firebase/serviceAccountKey.json
